import type { Metadata } from "next";
import "./globals.css";
import { estedad } from "@/next-persian-fonts/estedad/index";
import Footer from "@/components/global/footer";
import { FaTelegramPlane, FaWhatsapp } from "react-icons/fa";
import Link from "next/link";
import { Toaster } from "react-hot-toast";
import NewNavbar from "@/components/global/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa">
      <body className={` ${estedad.className} antialiased relative`}>
        <Toaster position="top-center" />
        <NewNavbar />
        {children}
        <div className="fixed bottom-2 right-2 flex flex-col gap-1 z-50">
          {/* Telegram Button */}
          <Link
            href="https://t.me/YOUR_TELEGRAM_USERNAME"
            target="_blank"
            rel="noopener noreferrer"
            className="flex items-center justify-center w-14 h-14 bg-gradient-to-br from-blue-500/40 to-blue-600/40 hover:from-blue-500 hover:to-blue-800 backdrop-blur-sm text-white rounded-full shadow-lg hover:scale-110 hover:shadow-xl transition-all duration-300"
          >
            <FaTelegramPlane className="text-2xl" />
          </Link>

          {/* WhatsApp Button */}
          <Link
            href="https://wa.me/YOUR_NUMBER" // شماره رو با فرمت بین‌المللی بزن مثل 989123456789+
            target="_blank"
            rel="noopener noreferrer"
            className="flex items-center justify-center w-14 h-14 bg-gradient-to-br from-green-400/40 to-green-600/40 hover:from-green-500 hover:to-green-800 backdrop-blur-sm text-white rounded-full shadow-lg hover:scale-110 hover:shadow-xl transition-all duration-300"
          >
            <FaWhatsapp className="text-2xl" />
          </Link>
        </div>
        <Footer />
      </body>
    </html>
  );
}
