export const stepThemes = {
  default: {
    backgroundColor: "bg-gray-50",
    headingColor: "text-gray-900",
    descriptionColor: "text-gray-600",
    stepBoxColor: "bg-white",
    stepActiveColor: "bg-blue-50",
    stepCompletedColor: "bg-green-50",
    stepTextColor: "text-gray-700",
    stepActiveTextColor: "text-blue-700",
    stepCompletedTextColor: "text-green-700",
    connectionLineColor: "border-gray-300",
    numberColor: "bg-gray-200 text-gray-700",
    numberActiveColor: "bg-blue-500 text-white",
    numberCompletedColor: "bg-green-500 text-white",
  },
  blue: {
    backgroundColor: "bg-white",
    headingColor: "text-gray-900",
    descriptionColor: "text-gray-700",
    stepBoxColor: "bg-[#0A1D37]",
    stepActiveColor: "bg-blue-50",
    stepCompletedColor: "bg-blue-50",
    stepTextColor: "text-gray-50",
    stepDescriptionColor: "text-gray-400",
    stepActiveTextColor: "text-blue-700",
    stepCompletedTextColor: "text-blue-700",
    connectionLineColor: "border-gray-300",
    numberColor: "bg-gray-200 text-gray-700",
    numberActiveColor: "bg-blue-500 text-white",
    numberCompletedColor: "bg-blue-500 text-white",
  },

  dark: {
    backgroundColor: "bg-gray-900",
    headingColor: "text-white",
    descriptionColor: "text-gray-300",
    stepBoxColor: "bg-gray-800",
    stepActiveColor: "bg-blue-900",
    stepCompletedColor: "bg-green-900",
    stepTextColor: "text-gray-200",
    stepDescriptionColor: "text-gray-400",

    stepActiveTextColor: "text-blue-300",
    stepCompletedTextColor: "text-green-300",
    connectionLineColor: "border-gray-600",
    numberColor: "bg-gray-700 text-gray-300",
    numberActiveColor: "bg-blue-600 text-white",
    numberCompletedColor: "bg-green-600 text-white",
  },
  purple: {
    backgroundColor: "bg-gray-50",
    headingColor: "text-fuchsia-700",
    descriptionColor: "text-gray-600",
    stepBoxColor: "bg-gray-800",
    stepActiveColor: "bg-fuchsia-900",
    stepCompletedColor: "bg-green-900",
    stepTextColor: "text-gray-200",
    stepDescriptionColor: "text-gray-400",

    stepActiveTextColor: "text-fuchsia-300",
    stepCompletedTextColor: "text-green-300",
    connectionLineColor: "border-gray-600",
    numberColor: "bg-gray-700 text-gray-300",
    numberActiveColor: "bg-fuchsia-600 text-white",
    numberCompletedColor: "bg-green-600 text-white",
  },

  gradient: {
    backgroundGradient:
      "bg-gradient-to-br from-purple-100 via-pink-50 to-indigo-100",
    headingColor: "text-gray-900",
    descriptionColor: "text-gray-600",
    stepBoxColor: "bg-white/80 backdrop-blur-sm",
    stepActiveColor: "bg-purple-50",
    stepCompletedColor: "bg-green-50",
    stepTextColor: "text-gray-700",
    stepDescriptionColor: "text-gray-400",

    stepActiveTextColor: "text-purple-700",
    stepCompletedTextColor: "text-green-700",
    connectionLineColor: "border-purple-300",
    numberColor: "bg-purple-200 text-purple-700",
    numberActiveColor: "bg-purple-500 text-white",
    numberCompletedColor: "bg-green-500 text-white",
  },

  neon: {
    backgroundColor: "bg-black",
    headingColor: "text-white",
    descriptionColor: "text-gray-300",
    stepBoxColor: "bg-gray-900 border-cyan-500/30",
    stepActiveColor: "bg-cyan-900/30",
    stepCompletedColor: "bg-green-900/30",
    stepTextColor: "text-gray-200",
    stepDescriptionColor: "text-gray-400",

    stepActiveTextColor: "text-cyan-300",
    stepCompletedTextColor: "text-green-300",
    connectionLineColor: "border-cyan-500",
    numberColor: "bg-gray-800 text-gray-300",
    numberActiveColor: "bg-cyan-500 text-black",
    numberCompletedColor: "bg-green-500 text-black",
  },
  neonYellow: {
    backgroundColor: "bg-black",
    headingColor: "text-white",
    descriptionColor: "text-gray-300",
    stepBoxColor: "bg-gray-900 border-yellow-500/30",
    stepActiveColor: "bg-yellow-900/30",
    stepCompletedColor: "bg-yellow-900/30",
    stepTextColor: "text-gray-200",
    stepDescriptionColor: "text-gray-400",

    stepActiveTextColor: "text-yellow-300",
    stepCompletedTextColor: "text-yellow-300",
    connectionLineColor: "border-yellow-500",
    numberColor: "bg-gray-800 text-gray-300",
    numberActiveColor: "bg-yellow-500 text-black",
    numberCompletedColor: "bg-yellow-500 text-black",
  },

  minimal: {
    backgroundColor: "bg-white",
    headingColor: "text-gray-900",
    descriptionColor: "text-gray-500",
    stepBoxColor: "bg-gray-50",
    stepActiveColor: "bg-gray-100",
    stepCompletedColor: "bg-gray-100",
    stepTextColor: "text-gray-700",
    stepDescriptionColor: "text-gray-400",

    stepActiveTextColor: "text-gray-900",
    stepCompletedTextColor: "text-gray-900",
    connectionLineColor: "border-gray-200",
    numberColor: "bg-gray-300 text-gray-700",
    numberActiveColor: "bg-gray-700 text-white",
    numberCompletedColor: "bg-gray-900 text-white",
  },

  colorful: {
    backgroundGradient:
      "bg-gradient-to-br from-red-50 via-yellow-50 to-blue-50",
    headingColor: "text-gray-900",
    descriptionColor: "text-gray-600",
    stepBoxColor: "bg-white/20",
    stepDescriptionColor: "text-gray-400",

    stepActiveColor: "bg-blue-50",
    stepCompletedColor: "bg-green-50",
    stepTextColor: "text-gray-700",
    stepActiveTextColor: "text-blue-700",
    stepCompletedTextColor: "text-green-700",
    connectionLineColor: "border-rainbow",
    numberColor: "bg-gradient-to-r from-red-400 to-yellow-400 text-white",
    numberActiveColor:
      "bg-gradient-to-r from-blue-500 to-purple-500 text-white",
    numberCompletedColor:
      "bg-gradient-to-r from-green-500 to-teal-500 text-white",
  },
  green: {
    backgroundGradient:
      "bg-gradient-to-br from-green-50 via-gray-50 to-emerald-50",
    headingColor: "text-green-600",
    descriptionColor: "text-gray-600",
    stepBoxColor: "bg-white/20",
    stepActiveColor: "bg-green-50",
    stepCompletedColor: "bg-green-50",
    stepDescriptionColor: "text-gray-400",

    stepTextColor: "text-gray-700",
    stepActiveTextColor: "text-green-700",
    stepCompletedTextColor: "text-green-700",
    connectionLineColor: "border-rainbow",
    numberColor: "bg-gradient-to-r from-green-400 to-green-400 text-white",
    numberActiveColor:
      "bg-gradient-to-r from-green-500 to-green-500 text-white",
    numberCompletedColor:
      "bg-gradient-to-r from-green-500 to-green-500 text-white",
  },
  red: {
    backgroundGradient: "bg-gradient-to-t from-red-500 via-gray-50 to-rose-50",
    headingColor: "text-red-600",
    descriptionColor: "text-gray-600",
    stepBoxColor: "bg-white/20",
    stepActiveColor: "bg-red-50",
    stepCompletedColor: "bg-red-50",
    stepDescriptionColor: "text-gray-400",

    stepTextColor: "text-gray-700",
    stepActiveTextColor: "text-red-700",
    stepCompletedTextColor: "text-red-700",
    connectionLineColor: "border-rainbow",
    numberColor: "bg-gradient-to-r from-red-400 to-red-400 text-white",
    numberActiveColor: "bg-gradient-to-r from-red-500 to-red-500 text-white",
    numberCompletedColor: "bg-gradient-to-r from-red-500 to-red-500 text-white",
  },
};

export const ctaThemes = {
  primary: {
    backgroundColor: "bg-blue-600",
    headingColor: "text-white",
    descriptionColor: "text-blue-100",
    buttonBackground: "bg-white",
    buttonText: "text-blue-600",
    buttonHover: "hover:bg-blue-50",
  },

  success: {
    backgroundColor: "bg-green-600",
    headingColor: "text-white",
    descriptionColor: "text-green-100",
    buttonBackground: "bg-white",
    buttonText: "text-green-600",
    buttonHover: "hover:bg-green-50",
  },
  warning: {
    backgroundColor: "bg-yellow-500",
    headingColor: "text-white",
    descriptionColor: "text-yellow-100",
    buttonBackground: "bg-white",
    buttonText: "text-yellow-600",
    buttonHover: "hover:bg-yellow-50",
  },
  danger: {
    backgroundColor: "bg-red-600",
    headingColor: "text-white",
    descriptionColor: "text-red-100",
    buttonBackground: "bg-white",
    buttonText: "text-red-600",
    buttonHover: "hover:bg-red-50",
  },
  purple: {
    backgroundColor: "bg-fuchsia-600",
    headingColor: "text-white",
    descriptionColor: "text-fuchsia-100",
    buttonBackground: "bg-white",
    buttonText: "text-fuchsia-600",
    buttonHover: "hover:bg-fuchsia-50",
  },
  dark: {
    backgroundColor: "bg-gray-900",
    headingColor: "text-white",
    descriptionColor: "text-gray-300",
    buttonBackground: "bg-white",
    buttonText: "text-gray-900",
    buttonHover: "hover:bg-gray-100",
  },
  gradient: {
    backgroundGradient:
      "bg-gradient-to-r from-purple-600 via-pink-600 to-blue-600",
    headingColor: "text-white",
    descriptionColor: "text-purple-100",
    buttonBackground: "bg-white",
    buttonText: "text-purple-600",
    buttonHover: "hover:bg-purple-50",
  },
  light: {
    backgroundColor: "bg-gray-100",
    headingColor: "text-gray-900",
    descriptionColor: "text-gray-600",
    buttonBackground: "bg-blue-600",
    buttonText: "text-white",
    buttonHover: "hover:bg-blue-700",
    borderColor: "border-gray-200",
  },
};

export const splitSectionThemes = {
  default: {
    background: "bg-gray-50",
    subHeading: "bg-gray-800 text-gray-300",

    textBoxBg: "bg-white",
    heading: "text-gray-900",
    description: "text-gray-600",
    button: "bg-blue-600 text-white hover:bg-blue-700",
  },
  dark: {
    background: "bg-gray-900",
    subHeading: "bg-gray-800 text-gray-300",
    textBoxBg: "bg-transparent",
    heading: "text-white",
    description: "text-gray-300",
    button: "bg-blue-500 text-white hover:bg-blue-600",
  },
  darkGreen: {
    background: "bg-gray-900",
    subHeading: "bg-gray-800 text-gray-300",
    textBoxBg: "bg-transparent",
    heading: "text-white",
    description: "text-gray-300",
    button: "bg-emerald-500 text-white hover:bg-emerald-600",
  },
  gradient: {
    background: "bg-gradient-to-br from-purple-100 via-pink-50 to-indigo-100",
    subHeading: "bg-gray-800 text-gray-300",

    textBoxBg: "bg-white/80 backdrop-blur-md",
    heading: "text-gray-900",
    description: "text-gray-600",
    button: "bg-purple-600 text-white hover:bg-purple-700",
  },
  minimal: {
    background: "bg-white",
    subHeading: "bg-gray-800 text-gray-300",

    textBoxBg: "bg-gray-50",
    heading: "text-gray-900",
    description: "text-gray-500",
    button: "bg-gray-800 text-white hover:bg-gray-900",
  },
  blue: {
    background: "bg-white",
    subHeading: "bg-blue-100 text-blue-600",
    textBoxBg: "bg-transparent",
    heading: "text-blue-700",
    description: "text-gray-500",
    button: "bg-gray-800 text-white hover:bg-gray-900",
  },
};

export const themesWhyus = {
  default: {
    background: "bg-[#0A1D37]",
    textBoxBg: "bg-white/10",
    heading: "text-gray-100",
    description: "text-gray-50",
    button: "bg-blue-600 text-white hover:bg-blue-700",
  },
  dark: {
    background: "bg-gray-900",
    textBoxBg: "bg-gray-800",
    heading: "text-white",
    description: "text-gray-300",
    button: "bg-blue-500 text-white hover:bg-blue-600",
  },
  gradient: {
    background: "bg-gradient-to-br from-blue-400 to-white",
    textBoxBg: "bg-white/80 backdrop-blur-md",
    heading: "text-gray-900",
    description: "text-gray-600",
    button: "bg-blue-400 text-white  hover:bg-blue-600",
  },
  minimal: {
    background: "bg-white",
    textBoxBg: "bg-gray-50",
    heading: "text-gray-900",
    description: "text-gray-500",
    button: "bg-gray-800 text-white hover:bg-gray-900",
  },
  purple: {
    background: "bg-gray-50",
    textBoxBg: "bg-fuchsia-600",
    heading: "text-gray-50",
    description: "text-gray-300",
    button: "bg-gray-800 text-white hover:bg-gray-900",
  },
  green: {
    background: "bg-green-700",
    textBoxBg: "bg-white",
    heading: "text-green-800",
    description: "text-green-600",
    button: "bg-green-600 text-white hover:bg-green-700",
  },
  red: {
    background: "bg-red-50",
    textBoxBg: "bg-white",
    heading: "text-red-800",
    description: "text-red-600",
    button: "bg-red-600 text-white hover:bg-red-700",
  },
  yellow: {
    background: "bg-yellow-50",
    textBoxBg: "bg-white",
    heading: "text-yellow-800",
    description: "text-yellow-600",
    button: "bg-yellow-500 text-white hover:bg-yellow-600",
  },
};
export const faqData = [
  {
    id: "1",
    question: "چگونه می‌توانم حساب کاربری ایجاد کنم؟",
    answer:
      "برای ایجاد حساب کاربری، روی دکمه 'ثبت نام' کلیک کنید و اطلاعات مورد نیاز را وارد کنید. پس از تایید ایمیل، حساب شما فعال خواهد شد.",
    category: "حساب کاربری",
  },
  {
    id: "2",
    question: "آیا تراکنش‌ها امن هستند؟",
    answer:
      "بله، تمام تراکنش‌ها با استفاده از رمزنگاری SSL و پروتکل‌های امنیتی پیشرفته محافظت می‌شوند. اطلاعات شما کاملاً محرمانه نگهداری می‌شود.",
    category: "امنیت",
  },
  {
    id: "3",
    question: "چه مدت زمان برای تایید تراکنش نیاز است؟",
    answer:
      "معمولاً تراکنش‌ها در کمتر از 10 دقیقه تایید می‌شوند. در مواقع شلوغی ممکن است تا 30 دقیقه طول بکشد.",
    category: "تراکنش",
  },
  {
    id: "4",
    question: "آیا می‌توانم تراکنش خود را لغو کنم؟",
    answer:
      "تراکنش‌های تایید نشده را می‌توانید لغو کنید. پس از تایید، امکان لغو وجود ندارد اما می‌توانید تراکنش معکوس انجام دهید.",
    category: "تراکنش",
  },
  {
    id: "5",
    question: "چگونه با پشتیبانی تماس بگیرم؟",
    answer:
      "می‌توانید از طریق چت آنلاین، ایمیل یا تلفن با تیم پشتیبانی ما در تماس باشید. پشتیبانی ما 24/7 در خدمت شماست.",
    category: "پشتیبانی",
  },
  {
    id: "6",
    question: "کارمزد تراکنش‌ها چقدر است؟",
    answer:
      "کارمزد بسته به نوع تراکنش متفاوت است. معمولاً بین 0.1% تا 2% متغیر است. جزئیات کامل در بخش 'تعرفه‌ها' موجود است.",
    category: "هزینه‌ها",
  },
];
// اضافه کردن preset themes
export const faqThemes = {
  default: {
    backgroundColor: "bg-gray-50",
    headingColor: "text-gray-900",
    descriptionColor: "text-gray-600",
    questionColor: "text-gray-800",
    answerColor: "text-gray-600",
    iconColor: "text-blue-600",
    borderColor: "border-gray-200",
    activeColor: "text-blue-600",
  },
  blue: {
    backgroundColor: "bg-blue-50",
    headingColor: "text-blue-900",
    descriptionColor: "text-blue-700",
    questionColor: "text-blue-800",
    answerColor: "text-blue-600",
    iconColor: "text-blue-600",
    borderColor: "border-blue-200",
    activeColor: "text-blue-600",
  },
  dark: {
    backgroundColor: "bg-gray-900",
    headingColor: "text-white",
    descriptionColor: "text-gray-300",
    questionColor: "text-gray-800",
    answerColor: "text-gray-500",
    iconColor: "text-blue-400",
    borderColor: "border-gray-700",
    activeColor: "text-gray-900",
  },
  green: {
    backgroundColor: "bg-green-50",
    headingColor: "text-green-900",
    descriptionColor: "text-green-700",
    questionColor: "text-green-800",
    answerColor: "text-green-600",
    iconColor: "text-green-600",
    borderColor: "border-green-200",
    activeColor: "text-green-600",
  },
  minimal: {
    backgroundColor: "bg-white",
    headingColor: "text-gray-900",
    descriptionColor: "text-gray-600",
    questionColor: "text-gray-800",
    answerColor: "text-gray-600",
    iconColor: "text-gray-600",
    borderColor: "border-gray-100",
    activeColor: "text-gray-900",
  },
};

export const textBoxThemes = {
  default: {
    backgroundColor: "bg-white",
    headingColor: "text-gray-900",
    textColor: "text-gray-700",
    borderColor: "border-gray-200",
    scrollbarColor: "scrollbar-thumb-blue-500",
    scrollbarTrackColor: "scrollbar-track-gray-100",
  },
  dark: {
    backgroundColor: "bg-gray-900",
    headingColor: "text-white",
    textColor: "text-gray-300",
    borderColor: "border-gray-700",
    scrollbarColor: "scrollbar-thumb-gray-600",
    scrollbarTrackColor: "scrollbar-track-gray-800",
  },
  blue: {
    backgroundColor: "bg-blue-50",
    headingColor: "text-blue-600",
    textColor: "text-slate-800",
    borderColor: "border-blue-200",
    scrollbarColor: "scrollbar-thumb-blue-500",
    scrollbarTrackColor: "scrollbar-track-blue-100",
  },
  green: {
    backgroundColor: "bg-green-50",
    headingColor: "text-green-900",
    textColor: "text-green-800",
    borderColor: "border-green-200",
    scrollbarColor: "scrollbar-thumb-green-500",
    scrollbarTrackColor: "scrollbar-track-green-100",
  },
  minimal: {
    backgroundColor: "bg-gray-50",
    headingColor: "text-gray-800",
    textColor: "text-gray-600",
    borderColor: "border-gray-100",
    scrollbarColor: "scrollbar-thumb-gray-400",
    scrollbarTrackColor: "scrollbar-track-gray-50",
  },
  red: {
    backgroundColor: "bg-rose-700",
    headingColor: "text-rose-50",
    textColor: "text-gray-600",
    borderColor: "border-rose-100",
    scrollbarColor: "scrollbar-thumb-gray-400",
    scrollbarTrackColor: "scrollbar-track-gray-50",
  },
};

export const textBoxTypography = {
  small: {
    headingSize: "text-lg",
    textSize: "text-sm",
    lineHeight: "leading-relaxed",
    fontWeight: "font-normal",
  },
  medium: {
    headingSize: "text-xl md:text-2xl",
    textSize: "text-base",
    lineHeight: "leading-relaxed",
    fontWeight: "font-normal",
  },
  large: {
    headingSize: "text-2xl md:text-3xl",
    textSize: "text-lg",
    lineHeight: "leading-loose",
    fontWeight: "font-light",
  },
};

